name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "*.py"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'

      - name: Load data to database
        env:
          PGHOST: ${{ secrets.PG_HOST }}
          PGDATABASE: ${{ secrets.PG_DB }}
          PGUSER: ${{ secrets.PG_USER }}
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        run: |
          python main.py

      - name: Run stored procedures
        env:
          PGHOST: ${{ secrets.PG_HOST }}
          PGDATABASE: ${{ secrets.PG_DB }}
          PGUSER: ${{ secrets.PG_USER }}
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        run: |
          psql -h $PGHOST -d $PGDATABASE -U $PGUSER -f proc_data_warehouse.sql
          psql -h $PGHOST -d $PGDATABASE -U $PGUSER -f procedure_datawarehouse.sql

